<?php
// install.php - Flight Log Installer
if (file_exists('installed.lock')) {
    echo "<div class='container my-4'><div class='alert alert-info'><h2>Installation Already Completed</h2><p>The system appears to be already installed. To reinstall, please remove the 'installed.lock' file.</p></div></div>";
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $db_host     = trim($_POST['db_host']);
    $db_username = trim($_POST['db_username']);
    $db_password = $_POST['db_password'];
    $db_name     = trim($_POST['db_name']);

    try {
        $pdo = new PDO("mysql:host=$db_host", $db_username, $db_password);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `$db_name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        $pdo->exec("USE `$db_name`");
        $sql_file = 'database.sql';
        if (!file_exists($sql_file)) {
            die("Error: 'database.sql' file not found.");
        }
        $sql_commands = file_get_contents($sql_file);
        $commands = array_filter(array_map('trim', explode(";", $sql_commands)));
        foreach ($commands as $command) {
            if (!empty($command)) {
                $pdo->exec($command);
            }
        }
        $config_content = "<?php\n";
        $config_content .= "// db.php generated by installer\n";
        $config_content .= "\$host = '" . addslashes($db_host) . "';\n";
        $config_content .= "\$db   = '" . addslashes($db_name) . "';\n";
        $config_content .= "\$user = '" . addslashes($db_username) . "';\n";
        $config_content .= "\$pass = '" . addslashes($db_password) . "';\n";
        $config_content .= "\$charset = 'utf8mb4';\n\n";
        $config_content .= "\$options = [\n";
        $config_content .= "    PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,\n";
        $config_content .= "    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,\n";
        $config_content .= "    PDO::ATTR_EMULATE_PREPARES   => false,\n";
        $config_content .= "];\n\n";
        $config_content .= "try {\n";
        $config_content .= "    \$pdo = new PDO(\"mysql:host=\$host;dbname=\$db;charset=\$charset\", \$user, \$pass, \$options);\n";
        $config_content .= "} catch (\\PDOException \$e) {\n";
        $config_content .= "    throw new \\PDOException(\$e->getMessage(), (int)\$e->getCode());\n";
        $config_content .= "}\n";
        file_put_contents('db.php', $config_content);
        file_put_contents('installed.lock', 'Installed on ' . date('Y-m-d H:i:s'));
        echo "<div class='container my-4'><div class='alert alert-success'><h2>Installation Successful</h2><p>The Flight Log website has been installed successfully.</p><p><strong>Important:</strong> For security, please remove or rename the <code>install.php</code> file.</p></div></div>";
    } catch (PDOException $e) {
        echo "<div class='container my-4'><div class='alert alert-danger'><h2>Installation Error</h2><p>Error: " . htmlspecialchars($e->getMessage()) . "</p></div></div>";
    }
} else {
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Flight Log Installer</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body { font-family: Arial, sans-serif; background: #f5f5f5; }
  </style>
</head>
<body>
  <div class="container my-4">
    <div class="card">
      <div class="card-header">
        <h2>Flight Log Installer</h2>
      </div>
      <div class="card-body">
        <p>Please enter your database credentials below. (Ensure the MySQL user has sufficient privileges.)</p>
        <form method="post" action="install.php">
          <div class="mb-3">
            <label for="db_host" class="form-label">Database Host:</label>
            <input type="text" class="form-control" name="db_host" id="db_host" value="localhost" required>
          </div>
          <div class="mb-3">
            <label for="db_username" class="form-label">Database Username:</label>
            <input type="text" class="form-control" name="db_username" id="db_username" required>
          </div>
          <div class="mb-3">
            <label for="db_password" class="form-label">Database Password:</label>
            <input type="password" class="form-control" name="db_password" id="db_password" required>
          </div>
          <div class="mb-3">
            <label for="db_name" class="form-label">Database Name:</label>
            <input type="text" class="form-control" name="db_name" id="db_name" value="flightlog" required>
          </div>
          <button type="submit" class="btn btn-primary">Install</button>
        </form>
      </div>
    </div>
  </div>
  <!-- Bootstrap JS Bundle -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
<?php
}
?>
