<?php
// install.php - Simple installer for the Flight Log website

// Prevent reinstallation.
if (file_exists('installed.lock')) {
    echo "<h2>Installation Already Completed</h2>";
    echo "<p>The system appears to be already installed. To reinstall, please remove the 'installed.lock' file.</p>";
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // (Optional: CSRF token verification could be added here.)
    $db_host     = trim($_POST['db_host']);
    $db_username = trim($_POST['db_username']);
    $db_password = $_POST['db_password'];
    $db_name     = trim($_POST['db_name']);

    try {
        // Connect to MySQL without a database.
        $pdo = new PDO("mysql:host=$db_host", $db_username, $db_password);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

        // Create and select the database.
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `$db_name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        $pdo->exec("USE `$db_name`");

        // Read and execute SQL commands from database.sql.
        $sql_file = 'database.sql';
        if (!file_exists($sql_file)) {
            die("Error: 'database.sql' file not found.");
        }
        $sql_commands = file_get_contents($sql_file);
        $commands = array_filter(array_map('trim', explode(";", $sql_commands)));
        foreach ($commands as $command) {
            if (!empty($command)) {
                $pdo->exec($command);
            }
        }

        // Create the db.php configuration file.
        $config_content = "<?php\n";
        $config_content .= "// db.php generated by installer\n";
        $config_content .= "\$host = '" . addslashes($db_host) . "';\n";
        $config_content .= "\$db   = '" . addslashes($db_name) . "';\n";
        $config_content .= "\$user = '" . addslashes($db_username) . "';\n";
        $config_content .= "\$pass = '" . addslashes($db_password) . "';\n";
        $config_content .= "\$charset = 'utf8mb4';\n\n";
        $config_content .= "\$options = [\n";
        $config_content .= "    PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,\n";
        $config_content .= "    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,\n";
        $config_content .= "    PDO::ATTR_EMULATE_PREPARES   => false,\n";
        $config_content .= "];\n\n";
        $config_content .= "try {\n";
        $config_content .= "    \$pdo = new PDO(\"mysql:host=\$host;dbname=\$db;charset=\$charset\", \$user, \$pass, \$options);\n";
        $config_content .= "} catch (\\PDOException \$e) {\n";
        $config_content .= "    throw new \\PDOException(\$e->getMessage(), (int)\$e->getCode());\n";
        $config_content .= "}\n";
        file_put_contents('db.php', $config_content);

        // Create an installation lock file.
        file_put_contents('installed.lock', 'Installed on ' . date('Y-m-d H:i:s'));

        echo "<h2>Installation Successful</h2>";
        echo "<p>The Flight Log website has been installed successfully.</p>";
        echo "<p><strong>Important:</strong> For security, please remove or rename the <code>install.php</code> file.</p>";
    } catch (PDOException $e) {
        echo "<h2>Installation Error</h2>";
        echo "<p>Error: " . htmlspecialchars($e->getMessage()) . "</p>";
    }
} else {
    require_once('functions.php');
    ?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Flight Log Installer</title>
        <style>
            body { font-family: Arial, sans-serif; background: #f5f5f5; }
            .container { max-width: 600px; margin: 50px auto; padding: 20px; background: #fff; border: 1px solid #ccc; }
            label { display: block; margin-top: 10px; }
            input[type="text"], input[type="password"] { width: 100%; padding: 8px; box-sizing: border-box; }
            input[type="submit"] { margin-top: 15px; padding: 10px 20px; background: #003366; color: #ffcc00; border: none; cursor: pointer; }
        </style>
    </head>
    <body>
    <div class="container">
        <h2>Flight Log Installer</h2>
        <p>Please enter your database credentials below. (Make sure the MySQL user has sufficient privileges.)</p>
        <form method="post" action="install.php">
            <label for="db_host">Database Host:</label>
            <input type="text" name="db_host" id="db_host" value="localhost" required>
            
            <label for="db_username">Database Username:</label>
            <input type="text" name="db_username" id="db_username" required>
            
            <label for="db_password">Database Password:</label>
            <input type="password" name="db_password" id="db_password" required>
            
            <label for="db_name">Database Name:</label>
            <input type="text" name="db_name" id="db_name" value="flightlog" required>
            
            <input type="submit" value="Install">
        </form>
    </div>
    </body>
    </html>
    <?php
}
?>
